package main

import (
 "crypto/md5"; "crypto/rand"; "crypto/tls"; "database/sql"; "encoding/binary"; "encoding/hex"; "encoding/json"; "errors"; "fmt"; "html"; "html/template"; "io"; "log"; "net"; "net/http"; "net/netip"; "os"; "path/filepath"; "sort"; "strconv"; "strings"; "sync"; "time"
 _ "modernc.org/sqlite"
 "golang.org/x/crypto/bcrypt"
)

type RadiusSession struct { ID, Username, IP string `json:"-"` }
type Identity struct { Username, IP string }
type Firewall struct { ID int; Name, Vendor, Address, Secret string; VerifyTLS, Enabled bool; LastStatus string; LastSync time.Time }
type User struct { ID int; Username, Mode, Password string }
type Config struct { RadiusURL, RadiusAPIKey, RadiusHost, RadiusSecret, TenantID string; VerifyTLS bool; RadiusAuthPort, RadiusAcctPort, PollSeconds, FullMinutes, InterimSeconds int }
type App struct { db *sql.DB; httpc *http.Client; mu sync.Mutex; sourceMu sync.Mutex }
func validateSeconds(x int) int { if x<5{return 5}; return x }; func validateMinutes(x int) int { if x<1{return 1}; return x }; func validateInterim(x int) int {if x<10{return 10};return x}
func desired(rows []RadiusSession) map[string]Identity { out:=map[string]Identity{}; for _,s:=range rows { if s.Username=="" {continue}; ip,err:=netip.ParseAddr(s.IP); if err!=nil||!ip.Is4(){continue}; if _,ok:=out[s.IP];!ok {out[s.IP]=Identity{s.Username,s.IP}} }; return out }
func diff(old, now map[string]Identity)([]Identity,[]Identity){var add,del []Identity;for ip,n:=range now {if o,ok:=old[ip];!ok||o.Username!=n.Username {add=append(add,n);if ok {del=append(del,o)}}};for ip,o:=range old{if _,ok:=now[ip];!ok{del=append(del,o)}};return add,del}
func main(){ data:=os.Getenv("DATA_DIR");if data==""{data="/data"};os.MkdirAll(data,0700); db,err:=sql.Open("sqlite",filepath.Join(data,"identity-sync.db"));if err!=nil{log.Fatal(err)}; a:=&App{db:db,httpc:&http.Client{Timeout:12*time.Second}};a.db.SetMaxOpenConns(1);a.db.SetMaxIdleConns(1);a.db.Exec("PRAGMA busy_timeout=5000");a.db.Exec("PRAGMA journal_mode=WAL");if err=a.init();err!=nil{log.Fatal(err)};if err=a.initExtras();err!=nil{log.Fatal(err)};go a.scheduler(); mux:=http.NewServeMux();mux.HandleFunc("/healthz",a.health);mux.HandleFunc("/login",a.login);mux.HandleFunc("/logout",a.logout);mux.HandleFunc("/",a.home);mux.HandleFunc("/settings",a.settings);mux.HandleFunc("/firewalls",a.firewalls);mux.HandleFunc("/admins",a.admins);mux.HandleFunc("/sync",a.syncNow);mux.HandleFunc("/test/radius",a.testRadius);mux.HandleFunc("/test/firewall",a.testFirewall);mux.HandleFunc("/firewall/mappings/delete",a.deleteMappings);mux.HandleFunc("/firewall/delete",a.deleteFirewall);mux.HandleFunc("/firewall/identities",a.firewallIdentities);mux.HandleFunc("/manual",a.manual);mux.HandleFunc("/debug",a.debug);mux.HandleFunc("/debug/tail",a.debugTail);mux.HandleFunc("/stats",a.stats);mux.HandleFunc("/config",a.configPage);mux.HandleFunc("/config/export",a.configExport);mux.HandleFunc("/config/import",a.configImport);mux.HandleFunc("/admin/end",a.adminEnd);mux.HandleFunc("/admin/delete",a.adminDelete);mux.HandleFunc("/manual/delete",a.manualDelete);log.Println("Identity Sync listening on :8080");log.Fatal(http.ListenAndServe(":8080",a.measured(mux))) }
func (a *App)init()error{ stmts:=[]string{`CREATE TABLE IF NOT EXISTS config(k TEXT PRIMARY KEY,v TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,mode TEXT NOT NULL CHECK(mode IN ('local','radius')),password TEXT)`,`CREATE TABLE IF NOT EXISTS firewalls(id INTEGER PRIMARY KEY,name TEXT NOT NULL,vendor TEXT NOT NULL,address TEXT NOT NULL,secret TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,last_status TEXT,last_sync TEXT)`,`CREATE TABLE IF NOT EXISTS identities(firewall_id INTEGER NOT NULL,ip TEXT NOT NULL,username TEXT NOT NULL,PRIMARY KEY(firewall_id,ip))`,`CREATE TABLE IF NOT EXISTS manual_identities(ip TEXT PRIMARY KEY,username TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS debug_log(id INTEGER PRIMARY KEY,created TEXT NOT NULL,message TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS web_sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,created TEXT NOT NULL,last_seen TEXT NOT NULL,acct_started INTEGER NOT NULL DEFAULT 0,last_acct TEXT)`};for _,s:=range stmts{if _,e:=a.db.Exec(s);e!=nil{return e}}; a.db.Exec("ALTER TABLE web_sessions ADD COLUMN last_acct TEXT");a.db.Exec("ALTER TABLE web_sessions ADD COLUMN input_octets INTEGER NOT NULL DEFAULT 0");a.db.Exec("ALTER TABLE web_sessions ADD COLUMN output_octets INTEGER NOT NULL DEFAULT 0"); a.db.Exec("ALTER TABLE firewalls ADD COLUMN verify_tls INTEGER NOT NULL DEFAULT 1"); var n int;a.db.QueryRow("SELECT count(*) FROM users").Scan(&n);if n==0{username:=os.Getenv("DEFAULT_ADMIN_USERNAME");if username==""{username="admin"};password:=os.Getenv("DEFAULT_ADMIN_PASSWORD");if password==""{return errors.New("DEFAULT_ADMIN_PASSWORD must be configured before first start")};h,_:=bcrypt.GenerateFromPassword([]byte(password),bcrypt.DefaultCost);_,err:=a.db.Exec("INSERT INTO users(username,mode,password) VALUES(?,'local',?)",username,string(h));if err!=nil{return err}}; defs:=map[string]string{"poll_seconds":"30","full_minutes":"60","interim_seconds":"60","radius_auth_port":"1812","radius_acct_port":"1813"};for k,v:=range defs{a.db.Exec("INSERT OR IGNORE INTO config(k,v) VALUES(?,?)",k,v)};return nil}
func (a *App)health(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");io.WriteString(w,`{"status":"ok"}`)}
func (a *App)cfg()Config{c:=Config{VerifyTLS:true};rows,e:=a.db.Query("SELECT k,v FROM config");if e!=nil{return c};defer rows.Close();m:=map[string]string{};for rows.Next(){var k,v string;rows.Scan(&k,&v);m[k]=v};c.RadiusURL=m["radius_url"];c.RadiusAPIKey=m["radius_api_key"];c.RadiusHost=m["radius_host"];c.RadiusSecret=m["radius_secret"];c.TenantID=m["tenant_id"];if m["radius_verify_tls"]=="false"{c.VerifyTLS=false};c.RadiusAuthPort,_=strconv.Atoi(m["radius_auth_port"]);c.RadiusAcctPort,_=strconv.Atoi(m["radius_acct_port"]);c.PollSeconds,_=strconv.Atoi(m["poll_seconds"]);c.FullMinutes,_=strconv.Atoi(m["full_minutes"]);c.InterimSeconds,_=strconv.Atoi(m["interim_seconds"]);c.PollSeconds=validateSeconds(c.PollSeconds);c.FullMinutes=validateMinutes(c.FullMinutes);c.InterimSeconds=validateInterim(c.InterimSeconds);return c}
func (a *App)user(r *http.Request)(User,bool){ck,e:=r.Cookie("ia_session");if e!=nil{return User{},false};var u User;var last string;e=a.db.QueryRow(`SELECT u.id,u.username,u.mode,COALESCE(u.password,''),s.last_seen FROM web_sessions s JOIN users u ON u.id=s.user_id WHERE s.token=?`,ck.Value).Scan(&u.ID,&u.Username,&u.Mode,&u.Password,&last);if e!=nil{return User{},false};t,_:=time.Parse(time.RFC3339,last);if time.Since(t)>8*time.Hour{a.endSession(a.cfg(),ck.Value);return User{},false};a.db.Exec("UPDATE web_sessions SET last_seen=? WHERE token=?",time.Now().UTC().Format(time.RFC3339),ck.Value);return u,true}
func (a *App)require(w http.ResponseWriter,r *http.Request)(User,bool){u,ok:=a.user(r);if !ok {http.Redirect(w,r,"/login",http.StatusFound)};return u,ok}
func token()string{b:=make([]byte,32);rand.Read(b);return hex.EncodeToString(b)}
func (a *App)login(w http.ResponseWriter,r *http.Request){if r.Method=="GET"{render(w,loginT,map[string]any{"Error":""});return};r.ParseForm();un,pw:=r.Form.Get("username"),r.Form.Get("password");var u User;e:=a.db.QueryRow("SELECT id,username,mode,COALESCE(password,'') FROM users WHERE username=?",un).Scan(&u.ID,&u.Username,&u.Mode,&u.Password);if e!=nil || (u.Mode=="local"&&bcrypt.CompareHashAndPassword([]byte(u.Password),[]byte(pw))!=nil) || (u.Mode=="radius"&&a.radiusAuth(a.cfg(),un,pw)!=nil){render(w,loginT,map[string]any{"Error":"Invalid credentials"});return};t:=token();now:=time.Now().UTC().Format(time.RFC3339);a.db.Exec("INSERT INTO web_sessions(token,user_id,created,last_seen,acct_started,last_acct) VALUES(?,?,?,?,1,?)",t,u.ID,now,now,now);http.SetCookie(w,&http.Cookie{Name:"ia_session",Value:t,Path:"/",HttpOnly:true,SameSite:http.SameSiteStrictMode});go a.account(a.cfg(),u.Username,t,1,0);http.Redirect(w,r,"/",303)}
func (a *App)logout(w http.ResponseWriter,r *http.Request){if c,e:=r.Cookie("ia_session");e==nil{var username string;a.db.QueryRow("SELECT u.username FROM web_sessions s JOIN users u ON u.id=s.user_id WHERE s.token=?",c.Value).Scan(&username);a.endSession(a.cfg(),c.Value);http.SetCookie(w,&http.Cookie{Name:"ia_session",Value:"",Path:"/",MaxAge:-1})};http.Redirect(w,r,"/login",303)}
func (a *App)home(w http.ResponseWriter,r *http.Request){u,ok:=a.require(w,r);if !ok{return};fs:=a.listFW();var cnt int;a.db.QueryRow("SELECT count(*) FROM identities").Scan(&cnt);render(w,homeT,map[string]any{"User":u,"FW":fs,"Count":cnt,"Notice":a.latestNotice(),"Page":"home"})}
func (a *App)settings(w http.ResponseWriter,r *http.Request){_,ok:=a.require(w,r);if !ok{return};if r.Method=="POST"{if !sameOrigin(r){http.Error(w,"invalid origin",403);return};r.ParseForm();vals:=map[string]string{"radius_url":r.Form.Get("radius_url"),"radius_api_key":r.Form.Get("radius_api_key"),"radius_host":r.Form.Get("radius_host"),"radius_secret":r.Form.Get("radius_secret"),"tenant_id":r.Form.Get("tenant_id"),"radius_verify_tls":r.Form.Get("radius_verify_tls"),"radius_auth_port":r.Form.Get("radius_auth_port"),"radius_acct_port":r.Form.Get("radius_acct_port"),"poll_seconds":strconv.Itoa(validateSeconds(atoi(r.Form.Get("poll_seconds"),30))),"full_minutes":strconv.Itoa(validateMinutes(atoi(r.Form.Get("full_minutes"),60))),"interim_seconds":strconv.Itoa(validateInterim(atoi(r.Form.Get("interim_seconds"),60)))};for k,v:=range vals{if v!=""{a.db.Exec("INSERT INTO config(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",k,v)}};if r.Form.Get("radius_verify_tls")!="on"{a.db.Exec("INSERT INTO config(k,v) VALUES('radius_verify_tls','false') ON CONFLICT(k) DO UPDATE SET v='false'")};http.Redirect(w,r,"/settings",303);return};render(w,settingsT,map[string]any{"C":a.cfg(),"Notice":a.latestNotice(),"Page":"settings"})}
func (a *App)firewalls(w http.ResponseWriter,r *http.Request){_,ok:=a.require(w,r);if !ok{return};if r.Method=="POST"{if !sameOrigin(r){http.Error(w,"invalid origin",403);return};r.ParseForm();addr:=strings.TrimSpace(r.Form.Get("address"));verify:=1;if r.Form.Get("verify_tls")!="on"{verify=0};if r.Form.Get("vendor")!="checkpoint"||addr==""||r.Form.Get("secret")==""{http.Error(w,"Checkpoint address and shared secret are required",400);return};a.db.Exec("INSERT INTO firewalls(name,vendor,address,secret,verify_tls,enabled,last_status) VALUES(?,?,?,?,?,1,'Not yet synchronized')",r.Form.Get("name"),"checkpoint",addr,r.Form.Get("secret"),verify);http.Redirect(w,r,"/firewalls",303);return};render(w,fwT,map[string]any{"FW":a.listFW(),"Notice":a.latestNotice(),"Page":"firewalls"})}
func (a *App)admins(w http.ResponseWriter,r *http.Request){_,ok:=a.require(w,r);if !ok{return};if r.Method=="POST"{if !sameOrigin(r){http.Error(w,"invalid origin",403);return};r.ParseForm();un,mode:=r.Form.Get("username"),r.Form.Get("mode");if un==""||(mode!="local"&&mode!="radius"){http.Error(w,"username and valid authentication mode required",400);return};p:="";if mode=="local"{if len(r.Form.Get("password"))<8{http.Error(w,"local password must be at least 8 characters",400);return};h,_:=bcrypt.GenerateFromPassword([]byte(r.Form.Get("password")),bcrypt.DefaultCost);p=string(h)};_,e:=a.db.Exec("INSERT INTO users(username,mode,password) VALUES(?,?,?)",un,mode,p);if e!=nil{http.Error(w,"username already exists",400);return};http.Redirect(w,r,"/admins",303);return};rows,_:=a.db.Query("SELECT id,username,mode FROM users ORDER BY username");defer rows.Close();var us []User;for rows.Next(){var u User;rows.Scan(&u.ID,&u.Username,&u.Mode);us=append(us,u)};render(w,adminT,map[string]any{"Users":us,"Page":"admins"})}
func (a *App)listFW()[]Firewall{rows,_:=a.db.Query("SELECT id,name,vendor,address,secret,verify_tls,enabled,COALESCE(last_status,''),COALESCE(last_sync,'') FROM firewalls ORDER BY id");defer rows.Close();var o []Firewall;for rows.Next(){var f Firewall;var en,verify int;var ts string;rows.Scan(&f.ID,&f.Name,&f.Vendor,&f.Address,&f.Secret,&verify,&en,&f.LastStatus,&ts);f.VerifyTLS=verify==1;f.Enabled=en==1;if ts!=""{f.LastSync,_=time.Parse(time.RFC3339,ts)};o=append(o,f)};return o}
func (a *App)syncNow(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method not allowed",405);return};if !sameOrigin(r){http.Error(w,"invalid origin",403);return};_,ok:=a.require(w,r);if !ok{return};if _,e:=a.radiusProbe(a.cfg());e!=nil{a.recordNotice("Manual synchronization failed before firewall updates: "+e.Error());http.Redirect(w,r,"/",303);return};a.recordNotice("Manual synchronization running...");a.sync(false);a.recordNotice("Manual synchronization completed; review firewall status below.");http.Redirect(w,r,"/",303)}
func atoi(s string,d int)int{n,e:=strconv.Atoi(s);if e!=nil{return d};return n}
func (a *App)scheduler(){lastFull:=time.Now();for {c:=a.cfg();full:=time.Since(lastFull)>=time.Duration(c.FullMinutes)*time.Minute;a.sync(full);a.expireSessions(c);a.interims(c);if full{lastFull=time.Now()};time.Sleep(time.Duration(c.PollSeconds)*time.Second)}}
func (a *App)fetch(c Config)([]RadiusSession,error){if c.RadiusURL==""||c.RadiusAPIKey==""{return nil,errors.New("RadiusStack URL and API key are not configured")};url:=strings.TrimRight(c.RadiusURL,"/")+"/api/sessions/active?limit=1000";q,e:=http.NewRequest("GET",url,nil);if e!=nil{return nil,e};q.Header.Set("X-API-Key",c.RadiusAPIKey);if c.TenantID!=""{q.Header.Set("X-Tenant-ID",c.TenantID)};cl:=*a.httpc;if !c.VerifyTLS{cl.Transport=&http.Transport{TLSClientConfig:&tls.Config{InsecureSkipVerify:true}}};a.debugLog("RadiusStack GET /api/sessions/active tenant="+c.TenantID+" verify_tls="+strconv.FormatBool(c.VerifyTLS));r,e:=cl.Do(q);if e!=nil{a.recordStat("radiusstack_api","failed","");a.debugLog("RadiusStack GET /api/sessions/active transport error: "+e.Error());return nil,e};defer r.Body.Close();a.recordStat("radiusstack_api",map[bool]string{true:"success",false:"failed"}[r.StatusCode==200],"");a.debugLog(fmt.Sprintf("RadiusStack GET /api/sessions/active -> HTTP %d content-length=%d",r.StatusCode,r.ContentLength));if r.StatusCode!=200{return nil,fmt.Errorf("RadiusStack returned HTTP %d",r.StatusCode)};var raw []struct{ID any `json:"radacctid"`;Username string `json:"username"`;IP string `json:"framedipaddress"`};body,e:=io.ReadAll(io.LimitReader(r.Body,2<<20));if e!=nil{return nil,e};if enabled,_:=a.debugState();enabled{a.debugLog("RadiusStack response body="+redactResponse(string(body),c.RadiusAPIKey))};if e=json.Unmarshal(body,&raw);e!=nil{return nil,e};out:=make([]RadiusSession,0,len(raw));for _,s:=range raw{out=append(out,RadiusSession{fmt.Sprint(s.ID),s.Username,s.IP})};a.trackSource(out);a.debugLog(fmt.Sprintf("RadiusStack response parsed: %d sessions, %d valid identities",len(out),len(desired(out))));return out,nil}
func (a *App)radiusProbe(c Config)(string,error){rows,e:=a.fetch(c);if e!=nil{return "",e};return fmt.Sprintf("RadiusStack API reachable: %d active sessions, %d valid IPv4 identity",len(rows),len(desired(rows))),nil}
func (a *App)debugLog(msg string){if a.db==nil{return};var v string;if a.db.QueryRow("SELECT v FROM config WHERE k='debug_enabled'").Scan(&v)==nil&&v=="true"{if result,e:=a.db.Exec("INSERT INTO debug_log(created,message) VALUES(?,?)",time.Now().UTC().Format(time.RFC3339),msg);e==nil{if id,e:=result.LastInsertId();e==nil&&id%100==0{a.trimDebug()}}}}
func (a *App)recordNotice(s string){a.db.Exec("INSERT INTO config(k,v) VALUES('last_notice',?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",s)}
func (a *App)latestNotice()string{var s string;a.db.QueryRow("SELECT v FROM config WHERE k='last_notice'").Scan(&s);return s}
func (a *App)testRadius(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method not allowed",405);return};if !sameOrigin(r){http.Error(w,"invalid origin",403);return};_,ok:=a.require(w,r);if !ok{return};s,e:=a.radiusProbe(a.cfg());if e!=nil{s="RadiusStack test failed: "+e.Error()};a.recordNotice(s);http.Redirect(w,r,"/settings",303)}
func (a *App)testFirewall(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method not allowed",405);return};if !sameOrigin(r){http.Error(w,"invalid origin",403);return};_,ok:=a.require(w,r);if !ok{return};id:=atoi(r.FormValue("id"),0);var f Firewall;var verify,en int;e:=a.db.QueryRow("SELECT id,name,vendor,address,secret,verify_tls,enabled FROM firewalls WHERE id=?",id).Scan(&f.ID,&f.Name,&f.Vendor,&f.Address,&f.Secret,&verify,&en);f.VerifyTLS=verify==1;f.VerifyTLS=r.FormValue("verify_tls")=="on";a.db.Exec("UPDATE firewalls SET verify_tls=? WHERE id=?",map[bool]int{true:1,false:0}[f.VerifyTLS],id);if e!=nil{a.recordNotice("Firewall test failed: firewall not found");http.Redirect(w,r,"/firewalls",303);return};e=a.cp(f,"show-identity",map[string]any{"ip-address":"127.0.0.1"});s:=fmt.Sprintf("Firewall %s Identity Web API reachable",f.Name);if e!=nil{s="Firewall test failed: "+e.Error()};a.recordNotice(s);http.Redirect(w,r,"/firewalls",303)}
func (a *App)firewallIdentities(w http.ResponseWriter,r *http.Request){_,ok:=a.require(w,r);if !ok{return};id:=atoi(r.FormValue("id"),0);var f *Firewall;for _,x:=range a.listFW(){if x.ID==id{z:=x;f=&z;break}};if f==nil{http.Error(w,"firewall not found",404);return};sessions,e:=a.fetch(a.cfg());if e!=nil{http.Error(w,"RadiusStack: "+e.Error(),502);return};w.Header().Set("Content-Type","text/html; charset=utf-8");fmt.Fprint(w,"<!doctype html><title>Firewall identities</title><style>body{font-family:system-ui;background:#0f172a;color:#e5e7eb;padding:28px}table{width:100%;border-collapse:collapse;background:#172033}th,td{padding:12px;text-align:left;border-bottom:1px solid #334155}th{color:#93c5fd}code{white-space:pre-wrap;color:#cbd5e1}.ok{color:#86efac}.bad{color:#fca5a5}</style><h1>Check Point identity mappings</h1><p>Firewall: "+html.EscapeString(f.Name)+" · RadiusStack active IPv4 sessions</p><table><tr><th>IP address</th><th>RadiusStack user</th><th>Check Point users</th><th>Status</th></tr>");for ip,want:=range desired(sessions){v,e:=a.cpRaw(*f,map[string]any{"ip-address":ip});users,status:="","Identity not present";cl:="bad";if e!=nil{status=e.Error()}else{users=fmt.Sprint(v["users"]);status=fmt.Sprint(v["message"]);if v["users"]!=nil{cl="ok"}};fmt.Fprintf(w,"<tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td class=%s>%s</td></tr>",html.EscapeString(ip),html.EscapeString(want.Username),html.EscapeString(users),cl,html.EscapeString(status))};fmt.Fprint(w,"</table>")}
func (a *App)manual(w http.ResponseWriter,r *http.Request){_,ok:=a.require(w,r);if !ok{return};if r.Method=="POST"{if !sameOrigin(r){http.Error(w,"invalid origin",403);return};r.ParseForm();for i,ip:=range r.Form["ip"]{u:=r.Form["username"];if i<len(u)&&net.ParseIP(ip)!=nil&&strings.TrimSpace(u[i])!=""{a.db.Exec("INSERT INTO manual_identities(ip,username) VALUES(?,?) ON CONFLICT(ip) DO UPDATE SET username=excluded.username",ip,strings.TrimSpace(u[i]))}};http.Redirect(w,r,"/manual",303);return};rows,_:=a.db.Query("SELECT ip,username FROM manual_identities ORDER BY ip");defer rows.Close();var x []Identity;for rows.Next(){var i Identity;rows.Scan(&i.IP,&i.Username);x=append(x,i)};render(w,manualT,map[string]any{"Items":x,"Page":"manual"})}
func (a *App)debug(w http.ResponseWriter,r *http.Request){_,ok:=a.require(w,r);if !ok{return};if r.Method=="POST"{if !sameOrigin(r){http.Error(w,"invalid origin",403);return};enabled:=r.FormValue("enabled");if enabled!="true"{enabled="false"};limit:=atoi(r.FormValue("limit"),200);if limit<10{limit=10};if limit>2000{limit=2000};a.db.Exec("INSERT INTO config(k,v) VALUES('debug_enabled',?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",enabled);a.db.Exec("INSERT INTO config(k,v) VALUES('debug_lines',?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",strconv.Itoa(limit));http.Redirect(w,r,"/debug",303);return};enabled,limit:=a.debugState();rows,_:=a.db.Query("SELECT created,message FROM debug_log ORDER BY id DESC LIMIT ?",limit);defer rows.Close();var x []string;for rows.Next(){var t,m string;rows.Scan(&t,&m);x=append(x,t+" "+m)};for i,j:=0,len(x)-1;i<j;i,j=i+1,j-1{x[i],x[j]=x[j],x[i]};render(w,debugT,map[string]any{"Lines":x,"Enabled":enabled,"Limit":limit,"Page":"debug"})}
func (a *App)deleteFirewall(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method not allowed",405);return};if !sameOrigin(r){http.Error(w,"invalid origin",403);return};_,ok:=a.require(w,r);if !ok{return};id:=atoi(r.FormValue("id"),0);var name string;if e:=a.db.QueryRow("SELECT name FROM firewalls WHERE id=?",id).Scan(&name);e!=nil{a.recordNotice("Delete firewall failed: firewall not found")}else{a.db.Exec("DELETE FROM identities WHERE firewall_id=?",id);a.db.Exec("DELETE FROM firewalls WHERE id=?",id);a.recordNotice("Removed firewall configuration: "+name)};http.Redirect(w,r,"/firewalls",303)}
func (a *App)deleteMappings(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method not allowed",405);return};if !sameOrigin(r){http.Error(w,"invalid origin",403);return};_,ok:=a.require(w,r);if !ok{return};id:=atoi(r.FormValue("id"),0);var f *Firewall;for _,x:=range a.listFW(){if x.ID==id{z:=x;f=&z;break}};if f==nil{a.recordNotice("Delete mappings failed: firewall not found");http.Redirect(w,r,"/firewalls",303);return};rows,e:=a.db.Query("SELECT ip FROM identities WHERE firewall_id=?",id);if e!=nil{a.recordNotice("Delete mappings failed: "+e.Error());http.Redirect(w,r,"/firewalls",303);return};var ips []string;for rows.Next(){var ip string;rows.Scan(&ip);ips=append(ips,ip)};rows.Close();source:="tracked";if len(ips)==0{sessions,err:=a.fetch(a.cfg());if err!=nil{a.recordNotice("Delete mappings failed: RadiusStack active-session lookup: "+err.Error());http.Redirect(w,r,"/firewalls",303);return};for ip:=range desired(sessions){ips=append(ips,ip)};source="RadiusStack active sessions"};for _,ip:=range ips{if e=a.cp(*f,"delete-identity",map[string]any{"ip-address":ip});e!=nil{a.recordNotice("Delete mappings stopped: "+e.Error());http.Redirect(w,r,"/firewalls",303);return}};a.db.Exec("DELETE FROM identities WHERE firewall_id=?",id);a.recordNotice(fmt.Sprintf("Deleted %d %s mappings from %s",len(ips),source,f.Name));http.Redirect(w,r,"/firewalls",303)}
func (a *App)sync(full bool){a.mu.Lock();defer a.mu.Unlock();sessions,e:=a.fetch(a.cfg());if e!=nil{for _,f:=range a.listFW(){a.status(f.ID,"RadiusStack error: "+e.Error())};return};now:=desired(sessions);mr,_:=a.db.Query("SELECT ip,username FROM manual_identities");for mr.Next(){var ip,u string;mr.Scan(&ip,&u);now[ip]=Identity{Username:u,IP:ip}};mr.Close();for _,f:=range a.listFW(){if !f.Enabled||f.Vendor!="checkpoint"{continue};a.recordStat("lookup","success","");old:=map[string]Identity{};rs,_:=a.db.Query("SELECT ip,username FROM identities WHERE firewall_id=?",f.ID);for rs.Next(){var i Identity;rs.Scan(&i.IP,&i.Username);old[i.IP]=i};rs.Close();add,del:=diff(old,now);if full{add=[]Identity{};for _,i:=range now{add=append(add,i)}};sort.Slice(add,func(i,j int)bool{return add[i].IP<add[j].IP});var fail error;for _,i:=range del{if e=a.cp(f,"delete-identity",map[string]any{"ip-address":i.IP});e!=nil{fail=e;break};a.db.Exec("DELETE FROM identities WHERE firewall_id=? AND ip=?",f.ID,i.IP)};if fail==nil{for _,i:=range add{if e=a.cp(f,"add-identity",map[string]any{"ip-address":i.IP,"user":i.Username,"identity-source":"RadiusStack Identity Sync","fetch-user-groups":0,"fetch-machine-groups":0,"calculate-roles":0,"roles":[]string{"API_Users"},"session-timeout":max(300,a.cfg().PollSeconds*4)});e!=nil{fail=e;break};a.db.Exec("INSERT INTO identities(firewall_id,ip,username) VALUES(?,?,?) ON CONFLICT(firewall_id,ip) DO UPDATE SET username=excluded.username",f.ID,i.IP,i.Username)}};if fail!=nil{a.recordStat("sync","failed","");a.status(f.ID,"Sync error: "+fail.Error())}else{if len(add)+len(del)==0{a.recordStat("lookup","no_change","")}else{a.recordStat("sync","success","")};a.status(f.ID,fmt.Sprintf("OK: %d identities (%d add/update, %d remove)",len(now),len(add),len(del)))}}}
func max(a,b int)int{if a>b{return a};return b}
func (a *App)status(id int,s string){a.db.Exec("UPDATE firewalls SET last_status=?,last_sync=? WHERE id=?",s,time.Now().UTC().Format(time.RFC3339),id)}
func (a *App)cpRaw(f Firewall,body map[string]any)(map[string]any,error){body["shared-secret"]=f.Secret;b,_:=json.Marshal(body);url:="https://"+strings.TrimRight(strings.TrimPrefix(strings.TrimPrefix(f.Address,"https://"),"http://"),"/")+"/_IA_API/v1.0/show-identity";q,e:=http.NewRequest("POST",url,strings.NewReader(string(b)));if e!=nil{return nil,e};q.Header.Set("Content-Type","application/json");cl:=*a.httpc;if !f.VerifyTLS{cl.Transport=&http.Transport{TLSClientConfig:&tls.Config{InsecureSkipVerify:true}}};a.debugLog("Check Point POST /_IA_API/v1.0/show-identity payload="+string(bSafeIdentity(body)));r,e:=cl.Do(q);if e!=nil{a.debugLog("Check Point show-identity error: "+e.Error());return nil,e};defer r.Body.Close();resp,e:=io.ReadAll(io.LimitReader(r.Body,8192));if e!=nil{return nil,e};a.debugLog(fmt.Sprintf("Check Point show-identity -> HTTP %d response=%s",r.StatusCode,redactResponse(string(resp),f.Secret)));if r.StatusCode<200||r.StatusCode>299{return nil,fmt.Errorf("Checkpoint show-identity HTTP %d",r.StatusCode)};var v map[string]any;e=json.Unmarshal(resp,&v);return v,e}
func (a *App)cp(f Firewall,cmd string,body map[string]any)error{safe,_:=json.Marshal(body);a.debugLog("Check Point POST /_IA_API/v1.0/"+cmd+" payload="+string(safe));body["shared-secret"]=f.Secret;b,_:=json.Marshal(body);url:="https://"+strings.TrimRight(strings.TrimPrefix(strings.TrimPrefix(f.Address,"https://"),"http://"),"/")+"/_IA_API/v1.0/"+cmd;q,e:=http.NewRequest("POST",url,strings.NewReader(string(b)));if e!=nil{return e};q.Header.Set("Content-Type","application/json");cl:=*a.httpc;if !f.VerifyTLS{cl.Transport=&http.Transport{TLSClientConfig:&tls.Config{InsecureSkipVerify:true}}};r,e:=cl.Do(q);if e!=nil{a.recordStat("firewall_update","failed","");a.debugLog("Check Point "+cmd+" transport failure: "+e.Error());return e};defer r.Body.Close();resp,_:=io.ReadAll(io.LimitReader(r.Body,8192));a.debugLog(fmt.Sprintf("Check Point %s -> HTTP %d response=%s",cmd,r.StatusCode,redactResponse(string(resp),f.Secret)));if r.StatusCode<200||r.StatusCode>299{a.recordStat("firewall_update","failed","");return fmt.Errorf("Checkpoint %s HTTP %d payload=%s response=%s",cmd,r.StatusCode,string(safe),redactResponse(strings.TrimSpace(string(resp)),f.Secret))};a.recordStat("firewall_update","success","");return nil}
// RADIUS uses PAP Access-Request and RFC2866 Accounting packets. Failures never reject a valid login.
func (a *App)radiusAuth(c Config,user,pass string)error{if c.RadiusHost==""||c.RadiusSecret==""{return errors.New("RADIUS authentication not configured")};id:=byte(time.Now().UnixNano());auth:=make([]byte,16);rand.Read(auth);attrs:=append(attr(1,[]byte(user)),attr(2,pap([]byte(pass),[]byte(c.RadiusSecret),auth))...);p:=packet(1,id,auth,attrs,[]byte(c.RadiusSecret));resp,e:=udp(c.RadiusHost,c.RadiusAuthPort,p);if e!=nil{return e};if len(resp)<1||resp[0]!=2{return errors.New("RADIUS rejected login")};return nil}
func (a *App)expireSessions(c Config){rows,e:=a.db.Query("SELECT s.token,u.username,s.created FROM web_sessions s JOIN users u ON u.id=s.user_id WHERE s.last_seen < ?",time.Now().Add(-15*time.Minute).UTC().Format(time.RFC3339));if e!=nil{return};type x struct{t,u,created string};var xs []x;for rows.Next(){var z x;rows.Scan(&z.t,&z.u,&z.created);xs=append(xs,z)};rows.Close();for _,z:=range xs{a.endSession(c,z.t)}}
func (a *App)interims(c Config){rows,e:=a.db.Query("SELECT s.token,u.username,s.created,COALESCE(s.last_acct,s.created) FROM web_sessions s JOIN users u ON u.id=s.user_id");if e!=nil{return};type x struct{t,u,created,last string};var xs []x;for rows.Next(){var z x;rows.Scan(&z.t,&z.u,&z.created,&z.last);xs=append(xs,z)};rows.Close();now:=time.Now();for _,z:=range xs{lt,_:=time.Parse(time.RFC3339,z.last);ct,_:=time.Parse(time.RFC3339,z.created);if now.Sub(lt)>=time.Duration(c.InterimSeconds)*time.Second{a.account(c,z.u,z.t,3,int(now.Sub(ct).Seconds()));a.db.Exec("UPDATE web_sessions SET last_acct=? WHERE token=?",now.UTC().Format(time.RFC3339),z.t)}}}
func (a *App)account(c Config,user,sid string,status int,sessionTime int){if c.RadiusHost==""||c.RadiusSecret==""||user==""{return};id:=byte(time.Now().UnixNano());auth:=make([]byte,16);rand.Read(auth);input,output:=a.sessionUsage(sid);attrs:=accountingAttrs(user,sid,status,sessionTime,input,output);p:=packet(4,id,auth,attrs,[]byte(c.RadiusSecret));resp,e:=udp(c.RadiusHost,c.RadiusAcctPort,p);if e!=nil{a.debugLog(fmt.Sprintf("RADIUS accounting status=%d user=%s failed: %v",status,user,e));a.recordStat("radius_accounting","failed","");return};if !validAccountingResponse(p,resp,[]byte(c.RadiusSecret)){a.debugLog(fmt.Sprintf("RADIUS accounting status=%d user=%s invalid response",status,user));a.recordStat("radius_accounting","failed","");return};a.debugLog(fmt.Sprintf("RADIUS accounting status=%d user=%s session_seconds=%d acknowledged",status,user,sessionTime));a.recordStat("radius_accounting","success","")}

func attr(t byte,v []byte)[]byte{return append([]byte{t,byte(len(v)+2)},v...)}
func pap(pass,secret,auth []byte)[]byte{n:=((len(pass)+15)/16)*16;if n==0{n=16};out:=make([]byte,n);copy(out,pass);prev:=auth;for i:=0;i<n;i+=16{h:=md5.New();h.Write(secret);h.Write(prev);x:=h.Sum(nil);for j:=0;j<16;j++{out[i+j]^=x[j]};prev=out[i:i+16]};return out}
func packet(code,id byte,auth,attrs,secret []byte)[]byte{p:=append([]byte{code,id,0,0},auth...);p=append(p,attrs...);binary.BigEndian.PutUint16(p[2:4],uint16(len(p)));if code==4{for i:=4;i<20;i++{p[i]=0};h:=md5.New();h.Write(p);h.Write(secret);copy(p[4:20],h.Sum(nil))};return p}
func udp(host string,port int,p []byte)([]byte,error){c,e:=net.DialTimeout("udp",net.JoinHostPort(host,strconv.Itoa(port)),3*time.Second);if e!=nil{return nil,e};defer c.Close();c.SetDeadline(time.Now().Add(5*time.Second));if _,e=c.Write(p);e!=nil{return nil,e};b:=make([]byte,4096);n,e:=c.Read(b);return b[:n],e}
func render(w http.ResponseWriter,s string,d any){w.Header().Set("Content-Type","text/html; charset=utf-8");template.Must(template.New("p").Parse(s)).Execute(w,d)}
